name: CD

on:
  workflow_run:
    workflows: ['CI']
    types:
      - completed
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up SSH key for deployment
      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.LIGHTSAIL_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.LIGHTSAIL_HOST }} >> ~/.ssh/known_hosts

      # Sync code to Lightsail instance
      - name: Deploy with rsync
        run: |
          rsync -az --delete \
            --exclude='.env' \
            --exclude='.git*' \
            --exclude='node_modules' \
            --exclude='dist' \
            ./ ${{ secrets.LIGHTSAIL_USER }}@${{ secrets.LIGHTSAIL_HOST }}:/home/${{ secrets.LIGHTSAIL_USER }}/app
        env:
          RSYNC_RSH: 'ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=yes'

      # Restart app using docker-compose
      - name: Restart App (docker CLI)
        run: |
          ssh -i ~/.ssh/id_ed25519 ${{ secrets.LIGHTSAIL_USER }}@${{ secrets.LIGHTSAIL_HOST }} "
            cd /home/${{ secrets.LIGHTSAIL_USER }}/app &&
            docker compose pull &&
            docker compose up -d --build
          "

      # Stop any existing Prisma Studio instances
      - name: Stop Previous Prisma Studio
        run: |
          ssh -i ~/.ssh/id_ed25519 ${{ secrets.LIGHTSAIL_USER }}@${{ secrets.LIGHTSAIL_HOST }} "
            docker exec whatsapp_bot pkill -f 'prisma studio' || true
          "

      # Start Prisma Studio in detached mode
      # SECURITY NOTES:
      # - Prisma Studio is bound to 127.0.0.1:5555 in docker-compose.yml
      # - This prevents direct external access to the database UI
      # - To access remotely, use SSH port forwarding:
      #   ssh -L 5555:localhost:5555 user@lightsail-host
      # - Consider additional security measures:
      #   * Implement authentication (Prisma Studio has no built-in auth)
      #   * Use a reverse proxy with authentication (nginx, Caddy)
      #   * Restrict access via firewall rules
      #   * Only expose when needed for debugging
      - name: Start Prisma Studio
        run: |
          ssh -i ~/.ssh/id_ed25519 ${{ secrets.LIGHTSAIL_USER }}@${{ secrets.LIGHTSAIL_HOST }} "
            docker exec -d whatsapp_bot npx prisma studio --port 5555 --hostname 0.0.0.0
          "
